name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    # - name: Hello world       # Name of step
    #   run: echo 'Hello world' # Command to run

    # - name: Hello world 2
    #   uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
    #   with:                                            # This section is needed if you need to pass arguments to the action
    #     who-to-greet: 'Mona the Octocat'

    - name: Build the C# code
      run: dotnet build

    - name: Run the C# dotnet test
      run: dotnet test

    - name: Install NPM Dependancies
      working-directory: ./DotnetTemplate.Web
      run: npm install

    - name: Build NPM Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm run build

    - name: Run linter on typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Run typescript tests
      working-directory: ./DotnetTemplate.Web
      run: npm t

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
